### ISSUE TITLE
Stratholme - Live Side - Mob Chains / Animations

### ISSUE THREAD

**Issue by Randysandy929** [VortexPrecision/PrecisionWoW#137]
Ran Stratholme Live side on 12/07/2020 as a feral druid named Feralhealth.

I noticed the following bugs:

- [x] 1. The rat cage drop down as you pass from one area to the next did not occur.
- [x] 2. The scarlet mobs inside the cathedral did not chain together, so we unintentionally were able to pick off a few mobs.

I'm not sure what rigor the animations are being considered on a side note, so I saw the following things but wouldn't be prioritize them.

- [x] 1. Timmy the Cruel spawned without clearing the scarlet mobs in the courtyard outside the temple.
- [x] 2. The cannonballs that fire into the Cannonmaster encounter had no animation and just started heavily damaging the party.
- [x] 3. The undead spawning after killing Balthazar spawned in their final locations instead of running from the beginning of the live side to that room.

Overall the class play felt good and the strength of mobs was appropriate, so great job so far! We opted to use the pre-raid BiS and still felt moderate ease but getting to that point may introduce challenge.

Thanks for all the hard work.

**Comment by VortexPrecision** [comment]
Thanks for the report, we will take a look.

**Comment by VortexPrecision** [comment]
https://www.youtube.com/watch?v=eWQysFFyjZA

**Comment by VortexPrecision** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19385

**Comment by VortexPrecision** [comment]
**Full report:**

Description:

- [x] The Crystals floating high above the three Ziggurats are not destroyed upon killing the five Thuzadin Acolytes (ID 10399) within. After you kill the 5th Thuzadin Acolyte, the crystal flashes for a moment and disappears.
- [x] The Rockwing Gargoyles (ID 10408) do not have the super long paths down the corridors of The Gauntlet. They just randomly walk around wherever they were spawned.


- [x] The trap gates do not trigger. Video of current core: https://youtu.be/4u3Hpdq44Pc Video of working trap gates: https://youtu.be/--IiC_Wuxfg?t=411

- [x] The gate into Slaughter Square is not supposed to open until the final Ziggurat crystal has been destroyed, which means until the final Thuzadin Acolyte (ID 10399) has died in the final Ziggurat. The gate currently opens as soon as the final of three bosses is killed at each Ziggurat.

- [x] After all of the Venom Belchers (ID 10417) and Bile Spewers (ID 10416) are dead, Ramstein the Gorger (ID 10439) appears at the steps of the Ziggurat but the doors do not open, and he does not walk out onto the ground. The doors are supposed to open and close behind Ramstein. Video of current core: https://youtu.be/Fugz-r3kEos

- [x] After you kill Ramstein and dispatch the wave of Mindless Undead that come running from the gate to the south, the doors are supposed to open again (this time permanently) and 4 Black Guard Sentry (ID 10394) are supposed to walk out in front of the steps of the Ziggurat. Instead, they are all stacked on top of each other, and they just stand at the top of the steps.

- [x] The door into Baron Rivendare's chamber is not supposed to open until the last Black Guard Sentry has died. It currently opens when Ramstein has died.

- [x] 8.Crimson hammersmith from the blacksmithing plans in Scarlet Strath should spawn, emote and run in when plans are opened. Not spawn ontop of plans and say nothing.
 https://youtu.be/8O56rBuNB4A?t=236
Black guard swordsmith in strath baron side from plans also should run in, not spawn ontop of plans.

- [x] 9.Object 176249 Scourge data. should be in each of the three strath undead ziggarauts, pooled with just one available. (Currently only one static spawn)
 http://wow.gamepedia.com/Scourge_Data
In zigaraut behind spider boss. https://youtu.be/6SRU-jG0N5c?t=430
The one behind banshee boss. https://youtu.be/g6c0HMk4cKE?t=25 (This is the only one we have)

 

- [x] 10.Hearthsinger Forresten needs more spawn points and pooling. The one currently is correct, heres the others.

https://s9.postimg.org/qsab8msgv/hearth1.png
https://s9.postimg.org/4udueudgf/hearth2.png
 https://s9.postimg.org/awlh5c1wf/hearth3.png

- [x] 11.Non lootable supply crates should do an animation of the box breaking when you get close enough to trigger it, probably pooled since they have seperate id's. Out of these the ones that do summon something (some just animate breaking open but nothing spawns) plagued insects/maggots/rats arent appearing either.
 https://s15.postimg.org/8lv4vm26z/dudcrate.png
 https://s15.postimg.org/o8me8zfyz/plagued_insect_crate.png
https://s15.postimg.org/muurdogpn/plagued_maggot_crate.png
 https://s15.postimg.org/a4qj0l8rf/plagued_rat_crate.png

- [x] 12.Undead postman from the openable mailboxes should spawn and run to mailbox, not spawn around it spread apart.

- [x] 13.Openable mailboxes do not spawn 'Postbox parcel' when opened. (spawns ontop of the opened mailbox door.https://s14.postimg.org/j35zc32b5/postboxparcel.png The loot from 'undead postmen' should be in the parcels. https://s16.postimg.org/hfdusi5lx/stuffromundeadpostmanshouldbeinmailboxparcelinst.png

- [x] 14.Signs on many of the stratholme signposts are floating off kilter.

- [x] 15.Archivist Galford is a movetype 1 like retail, Not 0. (From 2008 he moves here also, still does in retail)
https://youtu.be/8O56rBuNB4A?t=344

- [x] 16.Cannonmaster wileys riflemen adds should spawn in one position (they stack up strangely enough, as well as despawn even when aggroed, I guess so someone can't stand there and let a million summon.) https://s18.postimg.org/uvnm4ktl5/cannonadds.png also his cannon shouldn't melt people when walking around the corner into his room. They should shoot to the location the adds are when spawned, when cannonball is looted and used with them. The cannon will not shoot riflemen that are aggroed and pulled to the cannon. The riflemen should target the player upon spawn and fire at them.

- [x] 17.Grand crusader Dathrohan is missing yells. https://youtu.be/8O56rBuNB4A?t=385
 https://youtu.be/Nfg_cx1ZeVU?t=89
The 'summoned zombies' that spawn after he is killed should actually be 'skeletal guardian'. (Currently only one out group outside Dathrohans door, retail is what it was in wotlk with mobs all the way back through the scarlet building), just the extra friendlys rushing in since the revamp to kill them.

- [x] 18.Missing the patrol that runs from Dathrohans room when the three npcs just outside his doorway are slain. https://postimg.org/image/4dudmqwlp/8cfd2776/
 Another in first strath live hall after end mobs are killed. (speaks of the halls of light in yell)
https://youtu.be/B9EX8J2NgPM?t=458

- [x] 19.Patchwork horror should have his disease cloud aura up even when not in combat, dissapears on death. https://youtu.be/9OIcBvC7orw?t=326 https://youtu.be/aj_cZAC-Y3U?t=94

- [x] 20.Clearing the mob on the stairs at the entry to strath live should have nearby scarlets emote a yell and 'fall back' to cover the breach you made. (In this on retail they have already 'ran' to the stairs.) https://s29.postimg.org/5y91ddjav/stairskilledtwofrominfrontcomeandyell.png
 (Movie of Few spell fixes #5 above) Ramstein the gorger should walk out from barons zigaraut.
 https://www.youtube.com/watch?v=BuyAzTCl0N8

- [x] 22.Sothos and Jarien (Tier 0.5 brazier quest summoned bosses) Shouldn't spawn ontop of each other, also missing yells/ http://www.wowhead.com/object=181083 lootable chest, and their spirit npcs, also they don't seem to interact with each other like here says.
http://www.wowhead.com/npc=16101/jarien#comments
https://www.youtube.com/watch?v=-wfAjaAPoio
http://www.wowhead.com/npc=16103/spirit-of-jarien
http://www.wowhead.com/npc=16104/spirit-of-sothos

- [x] 23.Stratholme courier is missing visual emotes.

- [x] 24.Ghostly/spectral citizens. Missing their paths/emotes and spawn time. Roughly 5-6minutes they appear, some patrol some stand in groups of 2, emote for a little then despawn for another 5-6mins.

- [x] 25.Aurius in strath baron side needs to turn around and bow, then equip his weapon and face outwards https://youtu.be/vtTF1T02gjs?t=134 and should help on killing the baron if given the medal of faith.
 http://www.wowhead.com/npc=10917/aurius#comments

- [x] http://www.wowhead.com/npc=10516/the-unforgiven This boss isn't spawning, nor his adds, he should be stealthed. Note:His adds also will do a fast 'search' pathing semi circle if you manage to run past them and the unforgiven and dissapear before they aggro you.
http://www.wowhead.com/npc=10393/skul#comments Missing this rare.

- [x] http://www.wowhead.com/npc=11143/postmaster-malown
Missing this guy. He spawns when the third mailbox is opened.

- [x] Thuzadin Acolyte should cast a spell visual at their respective ziggaraut crystal every 5 seconds.
- [x] A yell also appears from a thuzadin acolyte (somewhere below stratholme) when each crystal of the three zigarauts is destroyed.

- [x] I believe stonespire should path, likely a pool with an existing gargoyle path

- [x] Lots of flee text emotes in strath live (below) when were these removed, i guess the undead version of the live don't flee ;P

Lfd strath live from around April 2010
Part 1 https://www.youtube.com/watch?v=v-iVcAbu0WQ
Part 2 https://www.youtube.com/watch?v=u1GGGOHkhzk
Part 3 https://www.youtube.com/watch?v=B9EX8J2NgPM
Part 4 https://www.youtube.com/watch?v=tSTWfNR4NLw
Part 5 https://www.youtube.com/watch?v=_YCY312TQMA
Part 6 https://www.youtube.com/watch?v=aj_cZAC-Y3U

Lfd strath ud
Part 1 https://www.youtube.com/watch?v=m4CxOAkkzCI
Part 2 https://www.youtube.com/watch?v=FvQxccYVvJI
Part 3 https://www.youtube.com/watch?v=AeHqp7B2XZo
Part 4 https://www.youtube.com/watch?v=6SRU-jG0N5c
Part 5 https://www.youtube.com/watch?v=BuyAzTCl0N8
