### ISSUE TITLE
[Argent Dawn] Vendor

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#462]
Missing enchants like Frost Mantle of the Dawn from vendors.

**Comment by Broker-Precision** [comment]
Not an issue.
In order to get this shoulder enchant from Argent Dawn you have to (1) be revered with Argent Dawn and (2) complete the quest [ Mantles of the Dawn](https://classic.wowhead.com/quest=5504/mantles-of-the-dawn) in which you turn in 10x [ Argent Dawn Valor Token](https://classic.wowhead.com/item=12844/argent-dawn-valor-token).

Once you have done that you can buy an infinite amount of the following enchants from Argent Dawn quartermasters for around 10g each.
[ Flame Mantle of the Dawn](https://classic.wowhead.com/item=18169/flame-mantle-of-the-dawn)
[ Frost Mantle of the Dawn](https://classic.wowhead.com/item=18170/frost-mantle-of-the-dawn)
[ Nature Mantle of the Dawn](https://classic.wowhead.com/item=18172/nature-mantle-of-the-dawn)
[ Arcane Mantle of the Dawn](https://classic.wowhead.com/item=18171/arcane-mantle-of-the-dawn)
[ Shadow Mantle of the Dawn](https://classic.wowhead.com/item=18173/shadow-mantle-of-the-dawn)
Becoming exalted with Argent Dawn and completing the quest [ Chromatic Mantle of the Dawn](https://classic.wowhead.com/quest=5517/chromatic-mantle-of-the-dawn) will allow you to buy a better shoulder enchant for around 40g.


Source: https://classic.wowhead.com/item=18170/frost-mantle-of-the-dawn#comments
 Chromatic Mantle of the Dawn
You only have to turn in the tokens once per character, after that you can buy as many enchants as you want.
You can only use these to enchant your own gear.
